import type { Metadata } from "next";
import "../globals.css";
import { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/Sidebar";
import { ReactQueryClientProvider } from "@/components/providers/ReactQueryClientProvider";
import { Lato, Poppins } from "next/font/google";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-lato",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryClientProvider>
        <html
          lang="en"
          className={`h-full ${lato.variable} ${poppins.variable}`}
          suppressHydrationWarning
        >
          <body className="antialiased min-h-screen">
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <AppSidebar />
                <div className="w-full flex flex-col">
                  <Header />
                  <main className="grow p-6">{children}</main>
                  <Footer />
                </div>
              </SidebarProvider>
            </ThemeProvider>
          </body>
        </html>
      </ReactQueryClientProvider>
    </ClerkProvider>
  );
}
